### ISSUE TITLE
define images location

### ISSUE THREAD

**Issue by henrypearce4D** [wanmeihuali/taichi_3d_gaussian_splatting#103]
Is there a way to define the image location for the dataset?

At the moment the images have to be in my  root taichi_3d_gaussian_splatting folder if absolute paths are not used in the transforms.json file.

the image path in the truck dataset in the json file is image\/ , usually this location is referenced next to the .json files, not the project root.

**Comment by wanmeihuali** [comment]
You can always put your image where ever you want, and create a soft link for your image folder in root taichi_3d_gaussian_splatting folder... On windows, I believe the shortcut shall also work.

**Comment by henrypearce4D** [comment]
Thats an interesting method I will have to test thankyou
