### ISSUE TITLE
Depth rasterization

### ISSUE THREAD

**Issue by Alexander0Yang** [wanmeihuali/taichi_3d_gaussian_splatting#112]
Nice work. But I'm slightly perplexed as to why the condition in https://github.com/wanmeihuali/taichi_3d_gaussian_splatting/blob/main/taichi_3d_gaussian_splatting/GaussianPointCloudRasterisation.py#L377) is `rgb_only` instead of `not rgb_only`.

**Comment by Alexander0Yang** [comment]
I suspect it could be the reason behind the wierd depth prediction.

**Comment by wanmeihuali** [comment]
Nice Catch! Will fix it in this [PR](https://github.com/wanmeihuali/taichi_3d_gaussian_splatting/pull/113)
The rgb_only flag is introduced recently because I found the depth/meta information causes some harm in inference FPS, sorry for not test it completely.
