### ISSUE TITLE
Rendering error when camera facing a blank area

### ISSUE THREAD

**Issue by npu-chenlin** [wanmeihuali/taichi_3d_gaussian_splatting#164]
Thank you for your extraordinary work. 
I wrote a program for rendering panoramic views and found that when the camera is facing a blank area, there will be rendering problems.
![image](https://github.com/wanmeihuali/taichi_3d_gaussian_splatting/assets/31912177/786381c8-4ce0-449c-935d-489ff4fdc3aa)

**Comment by yanzhoupan** [comment]
Currently we don't support panoramic views.
