### ISSUE TITLE
Rasterisation in validation is slower.

### ISSUE THREAD

**Issue by Dianazero** [wanmeihuali/taichi_3d_gaussian_splatting#52]
Hi, guys,
       Thank you for your excellent work. I am wondering why the rasterisation time cost during validation is much slower than during training？(~400ms  -> ~10ms)

**Comment by wanmeihuali** [comment]
Nice catch, I'll look into it.

**Comment by wanmeihuali** [comment]
The test on my local machine(RTX3090) shows that the inference time is actually still around 10ms for each frame...
What causes it to be slow is actually the SummaryWriter(tensorboard). I don't have a good way to accelerate it, so the current solution is to provide an option for the user to disable logging validation images, see this [PR](https://github.com/wanmeihuali/taichi_3d_gaussian_splatting/pull/54)

However, this observation is only for RTX3090, I think I did observe some very long inference on T4, may be due to different GPU arch/# of points. let's wait for the inference time data on T4 in that PR.

**Comment by Dianazero** [comment]
> The test on my local machine(RTX3090) shows that the inference time is actually still around 10ms for each frame... What causes it to be slow is actually the SummaryWriter(tensorboard). I don't have a good way to accelerate it, so the current solution is to provide an option for the user to disable logging validation images, see this [PR](https://github.com/wanmeihuali/taichi_3d_gaussian_splatting/pull/54)
> 
> However, this observation is only for RTX3090, I think I did observe some very long inference on T4, may be due to different GPU arch/# of points. let's wait for the inference time data on T4 in that PR.

Got it, thanks for your reply.

**Comment by atztao** [comment]
Maybe the same issue， training is getting slower and slower on RTX 3090.

`[Taichi] Starting on arch=cuda
  2% 500/30000 [01:26<1:28:34,  5.55it/s]num_valid_points=177099;
num_over_reconstructed: 44, num_under_reconstructed: 0
total valid points: 177099 -> 177143, num_densify_points: 44, num_fillable_densify_points: 44
num_transparent_points: 0, num_floaters_points: 0
  2% 600/30000 [02:24<4:46:42,  1.71it/s]3648 5472
num_valid_points=177143;
num_over_reconstructed: 59, num_under_reconstructed: 0
total valid points: 177143 -> 177202, num_densify_points: 59, num_fillable_densify_points: 59
num_transparent_points: 0, num_floaters_points: 0
  2% 700/30000 [03:32<6:07:39,  1.33it/s]num_valid_points=177202;
num_over_reconstructed: 42, num_under_reconstructed: 0
total valid points: 177202 -> 177244, num_densify_points: 42, num_fillable_densify_points: 42
num_transparent_points: 0, num_floaters_points: 0
  3% 800/30000 [04:50<6:58:37,  1.16it/s]3648 5472
num_valid_points=177244;
num_over_reconstructed: 25, num_under_reconstructed: 0
total valid points: 177244 -> 177269, num_densify_points: 25, num_fillable_densify_points: 25
num_transparent_points: 0, num_floaters_points: 0
  3% 900/30000 [06:32<8:57:17,  1.11s/it]num_valid_points=177269;
num_over_reconstructed: 42, num_under_reconstructed: 0
total valid points: 177269 -> 177311, num_densify_points: 42, num_fillable_densify_points: 42
num_transparent_points: 0, num_floaters_points: 0
  3% 1000/30000 [08:27<9:02:32,  1.12s/it]3648 5472
num_valid_points=177311;
num_over_reconstructed: 8, num_under_reconstructed: 0
total valid points: 177311 -> 177319, num_densify_points: 8, num_fillable_densify_points: 8
num_transparent_points: 0, num_floaters_points: 0
  4% 1100/30000 [10:40<8:34:48,  1.07s/it]num_valid_points=177319;
num_over_reconstructed: 60, num_under_reconstructed: 0
total valid points: 177319 -> 177379, num_densify_points: 60, num_fillable_densify_points: 60
num_transparent_points: 0, num_floaters_points: 0
  4% 1200/30000 [12:58<9:46:59,  1.22s/it] 3648 5472
num_valid_points=177379;
num_over_reconstructed: 70, num_under_reconstructed: 0
total valid points: 177379 -> 177449, num_densify_points: 70, num_fillable_densify_points: 70
num_transparent_points: 0, num_floaters_points: 0
  4% 1300/30000 [15:25<12:04:59,  1.52s/it]num_valid_points=177449;
num_over_reconstructed: 81, num_under_reconstructed: 0
total valid points: 177449 -> 177530, num_densify_points: 81, num_fillable_densify_points: 81
num_transparent_points: 0, num_floaters_points: 0
`

**Comment by wanmeihuali** [comment]
> Maybe the same issue， training is getting slower and slower on RTX 3090.
> 
> `[Taichi] Starting on arch=cuda 2% 500/30000 [01:26<1:28:34, 5.55it/s]num_valid_points=177099; num_over_reconstructed: 44, num_under_reconstructed: 0 total valid points: 177099 -> 177143, num_densify_points: 44, num_fillable_densify_points: 44 num_transparent_points: 0, num_floaters_points: 0 2% 600/30000 [02:24<4:46:42, 1.71it/s]3648 5472 num_valid_points=177143; num_over_reconstructed: 59, num_under_reconstructed: 0 total valid points: 177143 -> 177202, num_densify_points: 59, num_fillable_densify_points: 59 num_transparent_points: 0, num_floaters_points: 0 2% 700/30000 [03:32<6:07:39, 1.33it/s]num_valid_points=177202; num_over_reconstructed: 42, num_under_reconstructed: 0 total valid points: 177202 -> 177244, num_densify_points: 42, num_fillable_densify_points: 42 num_transparent_points: 0, num_floaters_points: 0 3% 800/30000 [04:50<6:58:37, 1.16it/s]3648 5472 num_valid_points=177244; num_over_reconstructed: 25, num_under_reconstructed: 0 total valid points: 177244 -> 177269, num_densify_points: 25, num_fillable_densify_points: 25 num_transparent_points: 0, num_floaters_points: 0 3% 900/30000 [06:32<8:57:17, 1.11s/it]num_valid_points=177269; num_over_reconstructed: 42, num_under_reconstructed: 0 total valid points: 177269 -> 177311, num_densify_points: 42, num_fillable_densify_points: 42 num_transparent_points: 0, num_floaters_points: 0 3% 1000/30000 [08:27<9:02:32, 1.12s/it]3648 5472 num_valid_points=177311; num_over_reconstructed: 8, num_under_reconstructed: 0 total valid points: 177311 -> 177319, num_densify_points: 8, num_fillable_densify_points: 8 num_transparent_points: 0, num_floaters_points: 0 4% 1100/30000 [10:40<8:34:48, 1.07s/it]num_valid_points=177319; num_over_reconstructed: 60, num_under_reconstructed: 0 total valid points: 177319 -> 177379, num_densify_points: 60, num_fillable_densify_points: 60 num_transparent_points: 0, num_floaters_points: 0 4% 1200/30000 [12:58<9:46:59, 1.22s/it] 3648 5472 num_valid_points=177379; num_over_reconstructed: 70, num_under_reconstructed: 0 total valid points: 177379 -> 177449, num_densify_points: 70, num_fillable_densify_points: 70 num_transparent_points: 0, num_floaters_points: 0 4% 1300/30000 [15:25<12:04:59, 1.52s/it]num_valid_points=177449; num_over_reconstructed: 81, num_under_reconstructed: 0 total valid points: 177449 -> 177530, num_densify_points: 81, num_fillable_densify_points: 81 num_transparent_points: 0, num_floaters_points: 0 `

Hi @atztao , training speed is another issue, but is shall not be that slow... can you provide more information about your training? such as version(commit id), profiling result(see this [config](https://github.com/wanmeihuali/taichi_3d_gaussian_splatting/blob/fe297719741dfec529a134e67bab93768373183b/config/test_sagemaker.yaml#L27)), and/or dataset? My local test on 3090 shows 20-30 FPS for training on tat_truck with 170k points...
