### ISSUE TITLE
Object centric dataset such as boots dataset 

### ISSUE THREAD

**Issue by fasogbon** [wanmeihuali/taichi_3d_gaussian_splatting#68]
Please can you provide training dataset for the boot sequence. I will like to try on object centric datasets and improve from there onwards. Thank you for your swift response. I just need to know the dataset, I can then run colmap myself if necessary to generate.

Thank you a lot for the great work

**Comment by wanmeihuali** [comment]
Will do that.  Also, the boot dataset is generated by a modified version of Blender plugin, and the boot is just a free mesh from the internet, but the plugin is now super buggy so I haven't released it yet. I'll try to release it by this weekend.

**Comment by wanmeihuali** [comment]
Here it is: https://github.com/wanmeihuali/taichi_3d_gaussian_splatting#train-on-example-objectboot
